%YAML:1.0
cache_root: ".cache"
yolov5_path: "./YOLOv5"
detector:
  yolov5weights: "yolov5m.pt"
  
stitcher:
  detect_qualitylevel: 0.1
  detect_cellH: 30
  track_min_rot: 0.5
  track_inlier_threshold: 1.0
  track_win: 8
  verbose: 1  # 0
  